# Generated by Django 5.0 on 2024-03-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0158_event_eventimage_eventbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_image',
            name='academic',
        ),
        migrations.RemoveField(
            model_name='academic_mentor',
            name='academic',
        ),
        migrations.RemoveField(
            model_name='create_group',
            name='author',
        ),
        migrations.RemoveField(
            model_name='jammingcontact',
            name='jamming',
        ),
        migrations.RemoveField(
            model_name='jammingimage',
            name='jamming',
        ),
        migrations.RemoveField(
            model_name='tutorcontact',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Academic_feestructure',
        ),
        migrations.DeleteModel(
            name='Academic_Image',
        ),
        migrations.DeleteModel(
            name='Academic_Mentor',
        ),
        migrations.DeleteModel(
            name='Academic_page',
        ),
        migrations.DeleteModel(
            name='Create_group',
        ),
        migrations.DeleteModel(
            name='jammingcontact',
        ),
        migrations.DeleteModel(
            name='Jamming',
        ),
        migrations.DeleteModel(
            name='jammingimage',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.DeleteModel(
            name='Tutorcontact',
        ),
    ]
